### ISSUE TITLE
Attempted import error: 'FrigadeChecklist' is not exported from '@frigade/react'

### ISSUE THREAD

**Issue by ronneldavis** [FrigadeHQ/javascript#146]
This was working previously on next version 14.0.0, but after updating to next version 14.1.0, it stops working.
 I am using @frigade/react version 1.38.31

**Comment by tuanvpham** [comment]
I ran into the same issue. I downgraded Next version down to 14.0.0 to resolve the issue for now, but hope Frigade team would look into it soon.

**Comment by christianmat** [comment]
Hey there! We're fixing this in the next release of the SDK this week. We'll post the version here as soon as it's out.

**Comment by christianmat** [comment]
Meanwhile, this might be a workaround for still using Next.js 14.1: https://github.com/vercel/next.js/discussions/61153

**Comment by tuanvpham** [comment]
@christianmat Thanks for the update. Look forward to the release.

**Comment by christianmat** [comment]
@tuanvpham @ronneldavis  we're still trying to figure out the root cause for the issue with Next.js. Meanwhile, you can consider updating to our beta SDK of 2.0 which will be the next major version of Frigade (although it requires 10-15 minutes of upgrades depending on how many flows you are using): https://frigade-v2-docs.mintlify.app/welcome

**Comment by tuanvpham** [comment]
It is great to hear you guys are working on the issue. Yea I am looking forward to version 2, hopefully it'll be out of beta soon.

**Comment by christianmat** [comment]
Sharing this related issue here in case it's helpful for folks: https://github.com/vercel/next.js/issues/60890

**Comment by christianmat** [comment]
@tuanvpham @ronneldavis confirming that this is a bug introduced by Next.js in 14.1.0 according to the above issue (https://github.com/vercel/next.js/issues/60890).

If you bump to the latest Next.js 14.1.1 canary it will automatically resolve itself. Hopefully Next.js team will soon release a GA version that fixes this.

If you don't want to be on the canary, the linked issue provides a series of workarounds. I tested @frigade/react with the latest canary and it appears to be stable.

**Comment by tuanvpham** [comment]
Thanks @christianmat. Appreciate it.
