### ISSUE TITLE
Horizontal checklist

### ISSUE THREAD

**Issue by Codemaine** [FrigadeHQ/javascript#271]
How do I accomplish something like this, with the checklist component?
(design is from the Frigade Figma file)

![image](https://github.com/FrigadeHQ/javascript/assets/64845752/b7a64d39-303e-4fbe-990b-e4b68383d5c6)

**Comment by brownrout** [comment]
Hey! Today the carousel checklist in Figma is only supported in the V1 of our sdk. We will likely add it to V2 sdk as well but we don’t have an ETA yet. For now, you could wire up your own horizontal checklist component to Frigade.

**Comment by Codemaine** [comment]
Oh okay. Is there a guide on how to do that?

**Comment by christianmat** [comment]
Hey @Codemaine -- yes, check this out: https://docs.frigade.com/v2/guides/custom
