### ISSUE TITLE
No complied css in Remix + Vite setup

### ISSUE THREAD

**Issue by edbella** [FrigadeHQ/javascript#296]
Hello. Frigade is awesome! however, I have run into an issue that I would like some guidance on

I'm using it in Remix + Vite setup. All works fine in development but when compiled for production, all css related styles are not compiled which cause major UI issues when a flow is activated.

Is there a way around this? I use tailwindcss for styling so I don't have any css-in-js styles on my project.

**Comment by dfltr** [comment]
Hi! Thanks for the bug report -- can you provide a codesandbox that reproduces the issue? It'll make debugging it easier.

As a first guess, we use [Emotion](https://emotion.sh/) for styling, so it's possible that it may not work if your specific stack/setup relies on pre-compiled styles. I'll be able to dig in more with a repro case though :)
