### ISSUE TITLE
visible Prop

### ISSUE THREAD

**Issue by Codemaine** [FrigadeHQ/javascript#318]
There should be a prop for all components, that shows whether the component is visible or not. This is useful for when the frontend would like to hide certain components, if the user hasn't completed their profile for example.

**Comment by christianmat** [comment]
Hey there, this is already possible via the `useFlow()` hook: https://docs.frigade.com/v2/sdk/hooks/flow
You can check `flow.isVisible()`

**Comment by Codemaine** [comment]
Oh alright. Could I get access to the Slack channel through my email: jermaineantwi22@gmail.com?

I'm having some issues setting up Frigade.
