### ISSUE TITLE
Support for SolidJS

### ISSUE THREAD

**Issue by timeowilliams** [FrigadeHQ/javascript#383]
Big fan of Frigade and the open source solution y'all provide. 

Many of us use SolidJS for development [(much less bloat and more performant than React)](https://dev.to/miracool/popularity-is-not-efficiency-solidjs-vs-reactjs-de7) and would love for frigade to support other frameworks outside of just React. 

Let me know if support or help is needed or if PR's are welcome.

**Comment by christianmat** [comment]
@timeowilliams feel free to fork this library if you're still interested in working on a SolidJS port. We'd be happy to link it in our docs once you get it working.
